### ISSUE TITLE
clboss crash after 5min

### ISSUE THREAD

**Issue by praptoumache** [ksedgwic/clboss#134]
when i start clboss it crashes after 5minutes
 this is the log right before plugin gets killed
```
 plugin-clboss: ChannelCreator: After reprioritization from IP binning: 0285c280641305f1641a9e08718d5f4b1sddfsdfsfeec4acfbefb5dde207ae4d, 03a718f9f5acf1a4b488b88f1fbc50b07fad37sdfsdf0652bf3b433d03a4, 0296b2db342fcf87ea94d981757fdf4d3e54sdfsdfsdf5d38dfdd73bf5c9, 0294ac3e099def03c12a37e30fe5364b1223fd60069869142ef96580c8439c2e0a, 022bd0aa893db4ac890e457cca8c83f112vhfdfgdfg53dab4bf904620503a78, 033d8656219478701227199cbd6f670335c8d408a92ae88b962c49d4dc0e83e025, 021dc5e3b994ef7f6f4d65ab61ccccysabbd512d9d6e3986346ff3665574f2c4d69, 02439112f98b6f4828e1a7426bfbece166bd36837d7dea4225a75ebd1d96864a07, 03fb822818be083e0a954db85257a2911a3d55458b8c1ea4124b157e865a836d12, 027e70d8859e090ed975b11cfa02109221482954a254dff185e4142188eb66518b, 02a20247f515sdfsdfce6a4287b5931d724068b7b88bbaead6380db3dd8e9a, 023d49fd88692d4d1f366eesdfsdfsdfsgdfh9c2266b036b440928e86cf3abe28d1894, 035e4ff418fc8b5554c5d9eea66396c227bd429a3251csdfsdf002ba215bfc226, 03f2f3b5ac54d7b4fbecc09sdfsdfsdfa7a2368e61075ffc98, 02687b2bfef5ab119857369ef4cba172e8658sdfsdfsd83a1faee2e5da1dc5, 03ad156742a9a9d0e82e0022f264d6857addfd534955d5e97de4a695bf8dd12af0, 0273497dc6db975876b03ec12004e05sdfsdfceb2e15d357d7327893997c, 033dee9c6a0afc40ffd8f27d68ef2sdfsdfdsd6f9bb607fb04c1d497a809
2022-05-31T11:55:12.379Z INFO    plugin-clboss: Killing plugin: exited during normal operation
```

**Comment by ZmnSCPxj** [comment]
What version are you using?  Can you add `--log-level=debug:plugin-clboss` to your lightningd command line/config file?

**Comment by praptoumache** [comment]
raspiblitz 1.7.2
bitcoin core 23.0
CLN 0.11.1
CLBoss 0.13A
```

2022-06-01T06:48:38.903Z DEBUG   lightningd: Calling rpc_command hook of plugin clboss
2022-06-01T06:48:38.904Z DEBUG   lightningd: Calling rpc_command hook of plugin clboss
2022-06-01T06:48:38.904Z DEBUG   plugin-clboss: Rpc out: listnodes {\"id\": \"02a20247f515d978cbf9e9ce6a4287b5931d724068b7b88bbaead6380db3dd8e9a\"}
2022-06-01T06:48:38.905Z DEBUG   plugin-clboss: Rpc out: listnodes {\"id\": \"033d8656219478701227199cbd6f670335c8d408a92ae88b962c49d4dc0e83e025\"}
2022-06-01T06:48:38.907Z DEBUG   lightningd: Plugin clboss returned from rpc_command hook call
2022-06-01T06:48:38.911Z DEBUG   plugin-clboss: Rpc in: listnodes {\"id\": \"033d8656219478701227199cbd6f670335c8d408a92ae88b962c49d4dc0e83e025\"} => {\"nodes\":[{\"nodeid\":\"033d8656219478701227199cbd6f670335c8d408a92ae88b962c49d4dc0e83e025\",\"alias\":\"bfx-lnd0\",\"color\":\"16b157\",\"last_timestamp\":1654032598,\"featur...
2022-06-01T06:48:38.911Z DEBUG   lightningd: Plugin clboss returned from rpc_command hook call
2022-06-01T06:48:38.914Z DEBUG   plugin-clboss: Rpc out: listnodes {\"id\": \"03f2f3b5ac54d7b4fbecc0978888b66fe318af6595b6344ba7a2368e61075ffc98\"}
2022-06-01T06:48:38.914Z DEBUG   plugin-clboss: Rpc in: listnodes {\"id\": \"02a20247f515d978cbf9e9ce6a4287b5931d724068b7b88bbaead6380db3dd8e9a\"} => {\"nodes\":[{\"nodeid\":\"02a20247f515d978cbf9e9ce6a4287b5931d724068b7b88bbaead6380db3dd8e9a\",\"alias\":\"Nasty_Nardo\",\"color\":\"095821\",\"last_timestamp\":1654065720,\"fea...
2022-06-01T06:48:38.914Z DEBUG   lightningd: Calling rpc_command hook of plugin clboss
2022-06-01T06:48:38.916Z DEBUG   plugin-clboss: Rpc out: listnodes {\"id\": \"033dee9c6a0afc40ffd8f27d68ef260f3e5e1c19e59c6f9bb607fb04c1d497a809\"}
2022-06-01T06:48:38.916Z DEBUG   lightningd: Plugin clboss returned from rpc_command hook call
2022-06-01T06:48:38.917Z DEBUG   lightningd: Calling rpc_command hook of plugin clboss
2022-06-01T06:48:38.918Z DEBUG   lightningd: Plugin clboss returned from rpc_command hook call
2022-06-01T06:48:38.922Z DEBUG   plugin-clboss: Rpc in: listnodes {\"id\": \"03f2f3b5ac54d7b4fbecc0978888b66fe318af6595b6344ba7a2368e61075ffc98\"} => {\"nodes\":[{\"nodeid\":\"03f2f3b5ac54d7b4fbecc0978888b66fe318af6595b6344ba7a2368e61075ffc98\",\"alias\":\"DonaldDuck\",\"color\":\"ff9a5b\",\"last_timestamp\":1654003420,\"feat...
2022-06-01T06:48:38.924Z DEBUG   lightningd: Calling rpc_command hook of plugin clboss
2022-06-01T06:48:38.924Z DEBUG   plugin-clboss: Rpc out: listnodes {\"id\": \"02687b2bfef5ab119857369ef4cba172e8658158c126f11a483a1faee2e5da1dc5\"}
2022-06-01T06:48:38.925Z DEBUG   plugin-clboss: Rpc in: listnodes {\"id\": \"033dee9c6a0afc40ffd8f27d68ef260f3e5e1c19e59c6f9bb607fb04c1d497a809\"} => {\"nodes\":[{\"nodeid\":\"033dee9c6a0afc40ffd8f27d68ef260f3e5e1c19e59c6f9bb607fb04c1d497a809\",\"alias\":\"??????MasterYoda???\",\"color\":\"278d39\",\"last_timestamp\":1654056...
2022-06-01T06:48:38.936Z INFO    plugin-clboss: Killing plugin: exited during normal operation
2022-06-01T06:48:38.936Z DEBUG   lightningd: Plugin clboss returned from rpc_command hook call
```

**Comment by ZmnSCPxj** [comment]
Hmmm.  How much memory is in your system?  Is CLBOSS getting hit by the OOM killer?  How many channels do you have? (My RaspPi with <20 channels works fine).

**Comment by m46nus** [comment]
CLBOSS still crashing at random times. I'm sending strace and log file. I'd like to get a coredump, but hasn't been able to create it yet. Does anyone know how? 


clboss version: v0.14.1
core-lightning version: "v24.11.1-modded"


```
epoll_pwait(5, [{events=EPOLLIN, data={u32=7, u64=8589934599}}], 64, 0, NULL, 8) = 1
ppoll([{fd=7, events=POLLIN}], 1, {tv_sec=0, tv_nsec=0}, NULL, 0) = 1 ([{fd=7, revents=POLLIN}], left {tv_sec=0, tv_nsec=0})
read(7, "{\"jsonrpc\":\"2.0\",\"id\":93,\"result"..., 4096) = 4096
ppoll([{fd=7, events=POLLIN}], 1, {tv_sec=0, tv_nsec=0}, NULL, 0) = 1 ([{fd=7, revents=POLLIN}], left {tv_sec=0, tv_nsec=0})
read(7, "1,\"htlc_maximum_msat\":2584147000"..., 4096) = 4096
ppoll([{fd=7, events=POLLIN}], 1, {tv_sec=0, tv_nsec=0}, NULL, 0) = 1 ([{fd=7, revents=POLLIN}], left {tv_sec=0, tv_nsec=0})
read(7, "m_msat\":12989608000,\"features\":\""..., 4096) = 4096
ppoll([{fd=7, events=POLLIN}], 1, {tv_sec=0, tv_nsec=0}, NULL, 0) = 1 ([{fd=7, revents=POLLIN}], left {tv_sec=0, tv_nsec=0})
read(7, "th\":11,\"delay\":34,\"htlc_minimum_"..., 4096) = 4096
ppoll([{fd=7, events=POLLIN}], 1, {tv_sec=0, tv_nsec=0}, NULL, 0) = 1 ([{fd=7, revents=POLLIN}], left {tv_sec=0, tv_nsec=0})
read(7, "y\":34,\"htlc_minimum_msat\":1,\"htl"..., 4096) = 990
ppoll([{fd=7, events=POLLIN}], 1, {tv_sec=0, tv_nsec=0}, NULL, 0) = 0 (Timeout)
epoll_pwait(5, [{events=EPOLLIN, data={u32=3, u64=4294967299}}], 64, 0, NULL, 8) = 1
read(3, "\1", 1)                        = 1
epoll_pwait(5, [], 64, 0, NULL, 8)      = 0
epoll_pwait(5, [], 64, 0, NULL, 8)      = 0
epoll_pwait(5, [], 64, 0, NULL, 8)      = 0
epoll_pwait(5, [], 64, 0, NULL, 8)      = 0
epoll_pwait(5, [], 64, 0, NULL, 8)      = 0
write(1, "{\"jsonrpc\": \"2.0\", \"method\": \"lo"..., 362) = 362
epoll_pwait(5, [], 64, 0, NULL, 8)      = 0
futex(0xaaab1ec5d558, FUTEX_WAKE_PRIVATE, 1) = 1
write(1, "{\"jsonrpc\": \"2.0\", \"method\": \"lo"..., 362) = 362
epoll_ctl(5, EPOLL_CTL_ADD, 3, {events=EPOLLIN, data={u32=3, u64=8589934595}}) = -1 EEXIST (File exists)
epoll_pwait(5, [], 64, 0, NULL, 8)      = 0
write(1, "{\"jsonrpc\": \"2.0\", \"id\": \"96/cln"..., 85) = 85
epoll_pwait(5, [], 64, 0, NULL, 8)      = 0
write(1, "{\"jsonrpc\": \"2.0\", \"method\": \"lo"..., 163) = 163
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], ~[KILL STOP RTMIN RT_1], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], ~[KILL STOP RTMIN RT_1], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
epoll_pwait(5, [], 64, 0, NULL, 8)      = 0
write(1, "{\"jsonrpc\": \"2.0\", \"method\": \"lo"..., 124) = 124
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7666e901e6b27100} ---
+++ killed by SIGSEGV +++
```



```

2025-01-24T08:30:44.394Z DEBUG   plugin-clboss: Rpc in: listchannels {\"source\": \"035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226\"} => {\"channels\":[{\"source\":\"035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226\",\"destination\":\"03fd3e0f2504e149b1907cab853712a213b182b8c972169fa3ad0...
2025-01-24T08:30:44.403Z DEBUG   plugin-clboss: Rpc in: listchannels {\"source\": \"03c2abfa93eacec04721c019644584424aab2ba4dff3ac9bdab4e9c97007491dda\"} => {\"channels\":[{\"source\":\"03c2abfa93eacec04721c019644584424aab2ba4dff3ac9bdab4e9c97007491dda\",\"destination\":\"029fe435040c8b665f731f2b0c81d039238ef1e3a1b1de0afac2b...
2025-01-24T08:30:44.462Z DEBUG   plugin-clboss: Rpc in: getroute {\"id\": \"02f4c77dcf12255ccf705c18b8d6b95e4f884910bf61e8aa21242607193a79da1b\", \"fromid\": \"035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226\", \"amount_msat\": 1, \"riskfactor\": 10, \"exclude\": [\"03fd3e0f2504e149b1907cab853712a213b182b8c972169fa3ad009b623533103f\"], \"fuzzpercent\": 0, \"maxhops\": 3} => {\"route\":[{\"id\":\"036578a930856b958fa6ee136cf27a1620c48a2280a3315257b33bd1b58174a776\",\"channel\":\"845308x2886x0\",\"direction\":0,\"amount_msat\":1001,\"delay\":43,\"styl...
2025-01-24T08:30:44.494Z INFO    plugin-clboss: Killing plugin: exited during normal operation
```

**Comment by tsjk** [comment]
I think this should be a new issue.  When you create that you can try to also add the output of
`lightning-cli -k getroute id="02f4c77dcf12255ccf705c18b8d6b95e4f884910bf61e8aa21242607193a79da1b" fromid="035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226" amount_msat=1 riskfactor=10 exclude='["03fd3e0f2504e149b1907cab853712a213b182b8c972169fa3ad009b623533103f"]' fuzzpercent=0 maxhops=3`

**Comment by m46nus** [comment]
I didn't want to create new issue, since this one is still open without a solution...

```
lightning-cli -k getroute id="02f4c77dcf12255ccf705c18b8d6b95e4f884910bf61e8aa21242607193a79da1b" fromid="035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226" amount_msat=1 riskfactor=10 exclude='["03fd3e0f2504e149b1907cab853712a213b182b8c972169fa3ad009b623533103f"]' fuzzpercent=0 maxhops=3
{
   "route": [
      {
         "id": "036578a930856b958fa6ee136cf27a1620c48a2280a3315257b33bd1b58174a776",
         "channel": "845308x2886x0",
         "direction": 0,
         "amount_msat": 1001,
         "delay": 43,
         "style": "tlv"
      },
      {
         "id": "02f4c77dcf12255ccf705c18b8d6b95e4f884910bf61e8aa21242607193a79da1b",
         "channel": "876847x1681x1",
         "direction": 1,
         "amount_msat": 1,
         "delay": 9,
         "style": "tlv"
      }
   ]
}
```

This is the command, nothing special I guess. It crashes at random operations.. Sometimes it crashes right after start and sometimes it runs couple of minutes...

IMHO, without the core dump it wont be analyzable. We need a backtrace... So either core dump or run it through gdb. But I don't know how to do it..

**Comment by m46nus** [comment]
```
Thread 1 "clboss" received signal SIGSEGV, Segmentation fault.
0x0000ffffab5d1fa8 in ?? () from /lib/aarch64-linux-gnu/libunwind.so.8
(gdb) bt
#0  0x0000ffffab5d1fa8 in ?? () from /lib/aarch64-linux-gnu/libunwind.so.8
#1  0x0000ffffab5d75d0 in _ULaarch64_is_signal_frame () from /lib/aarch64-linux-gnu/libunwind.so.8
#2  0x0000ffffab5d86f8 in _ULaarch64_step () from /lib/aarch64-linux-gnu/libunwind.so.8
#3  0x0000aaaad0cab174 in Util::BacktraceException<std::runtime_error>::capture_backtrace() ()
#4  0x0000aaaad109ec70 in Boss::Mod::RpcError::RpcError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Jsmn::Object) ()
#5  0x0000aaaad10a88e0 in Boss::Mod::Rpc::Impl::logging_command(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Json::Out) ()
#6  0x0000aaaad109edc4 in Boss::Mod::Rpc::command(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Json::Out) ()
#7  0x0000aaaad0e0333c in Boss::Mod::ChannelFinderByDistance::Run::step(Ln::NodeId const&) ()
#8  0x0000aaaad0e034f4 in Ev::Io<void>::then<Boss::Mod::ChannelFinderByDistance::Run::loop()::{lambda()#1}>(Boss::Mod::ChannelFinderByDistance::Run::loop()::{lambda()#1}) &&::{lambda(std::function<void ()>, std::function<void (std::__exception_ptr::exception_ptr)>)#1}::operator()(std::function<void ()>, std::function<void (std::__exception_ptr::exception_ptr)>) const::{lambda()#1}::operator()() const ()
#9  0x0000aaaad0caf27c in (anonymous namespace)::yield_handler(ev_loop*, ev_idle*, int) ()
#10 0x0000ffffab8242ac in ev_invoke_pending () from /lib/aarch64-linux-gnu/libev.so.4
#11 0x0000ffffab827ae8 in ev_run () from /lib/aarch64-linux-gnu/libev.so.4
#12 0x0000aaaad0cae1ac in Ev::start(Ev::Io<int>) ()
#13 0x0000aaaad0c821f4 in main ()

```

**Comment by ksedgwic** [comment]
Yikes, good catch!

👀 ...

--
Ken Sedgwick
Bonsai Software, Inc.
http://www.bonsai.com/ken/
(510) 269-7334
***@***.***
Public Key: http://www.bonsai.com/ken/ken.asc
GPG Fingerprint: 4695 E5B8 F781 BF85 4326  9639 BBFC E515 8602 5550

**Comment by ksedgwic** [comment]
Some thoughts ...

Here are the source locations where I think some of the key frames in the backtrace above are being called:
- frame 6 https://github.com/ZmnSCPxj/clboss/blob/v0.14.1/Boss/Mod/ChannelFinderByDistance.cpp#L216
- frame 5 https://github.com/ZmnSCPxj/clboss/blob/v0.14.1/Boss/Mod/Rpc.cpp#L429
- frame 4 https://github.com/ZmnSCPxj/clboss/blob/v0.14.1/Boss/Mod/Rpc.cpp#L389-L391
- frame 3 https://github.com/ZmnSCPxj/clboss/blob/v0.14.1/Boss/Mod/Rpc.cpp#L63

I don't think this is related to the `getroute` because the RPC command that is indicated by the stack backtrace is `rpc.command("listchannels", ...`

In your log snippet above you have other `Rpc in: listchannels` lines, I think maybe we succeeded at the `Rpc in: getroute` and then failed trying to do do another `listchannels` (but didn't quite make it to the `Rpc in: listchannels` log line.

Did the backtrace code cause the SEGV or was it's failure because we were already SEGV'd?

Is it similar to https://github.com/libunwind/libunwind/issues/68#issuecomment-470374652 ?

I'm still pondering, interested if others see stuff I'm missing or looking at incorrectly

**Comment by ksedgwic** [comment]
@m46nus Are there associated "Rpc out" logging lines in your log as well?  Is the output above filtered or grepped or are they not there?

**Comment by tsjk** [comment]
Just some questions...
So, this happens during the Djikstra calculations? Does it always?
How has clboss for aarch64 been built?
By the looks of lib paths this is a Debian system - right? I have these paths neither on my Void system nor my ArchLinuxARM system.

**Comment by m46nus** [comment]
The problem is in capture backtrace funcion.
```

        void capture_backtrace() {
                unw_cursor_t cursor;
                unw_context_t context;
                unw_getcontext(&context);
                unw_init_local(&cursor, &context);

                while (unw_step(&cursor) > 0 && backtrace_addresses_.size() < MAX_FRAMES) {
                        unw_word_t ip;
                        unw_get_reg(&cursor, UNW_REG_IP, &ip);
                        backtrace_addresses_.push_back(ip);
                }

                stack_depth = backtrace_addresses_.size();
        }

```
I used a workaround by disabling ENABLE_EXCEPTION_BACKTRACE and it's not crashing any more.

`./configure --disable-exception-backtrace`
